/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercise.ui;

//import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
//import javax.swing.JButton;
import javax.swing.SwingWorker;
import javax.swing.UIManager;

/**
 *
 * @author aungmrat
 */
public class Home extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

  /**
   * Creates new form Home
   */
  public Home() {
    initComponents();
    initCustomLogic();
    home();
    //onHoverAllButtons();
    btnRegister.setEnabled(false);
    btnFamilyMember.setEnabled(false);
    btnSpecialization.setEnabled(false);
    // JToggleButton ကို Switch ပုံစံ ဖြစ်စေရန် FlatLaf client property ကို သုံးခြင်

  }

  
  private void initCustomLogic() {
  rbDark.addItemListener(e -> {
    try {
        if (rbDark.isSelected()) {
            // Dark Mode သို့ ပြောင်းရန်
            com.formdev.flatlaf.FlatDarkLaf.setup();
        } else {
            // Light Mode သို့ ပြောင်းရန်
            com.formdev.flatlaf.FlatLightLaf.setup();
        }
        
        // Window တစ်ခုလုံးရှိ UI များကို Theme အသစ်ဖြင့် Update လုပ်ရန်
        javax.swing.SwingUtilities.updateComponentTreeUI(this); // this သည် JFrame ဖြစ်ရပါမည်
        
    } catch (Exception ex) {
        ex.printStackTrace();
    }
});}

//  private void onHoverAllButtons() {
//    onHoverButton(btnHome);
//    onHoverButton(btnRegister);
//    onHoverButton(btnFamilyMember);
//    onHoverButton(btnSpecialization);
//  }
//
//  private void onHoverButton(JButton button) {
//    button.putClientProperty(FlatClientProperties.STYLE,
//            "hoverBackground: #525080; "
//            + "foreground: #FFFFFF; "
//            + "hoverForeground: #FFFFFF; "
//            + "arc: 12;");
//  }

//  private void familyMember() {
//    FamilyMember familyMember = new FamilyMember();
//    switchPanel(familyMember);
//  }
//
//  private void studentRegister() {
//    StudentRegister studentRegister = new StudentRegister();
//    switchPanel(studentRegister);
//  }
//
//  private void specialization() {
//    Specialization specialization = new Specialization();
//    switchPanel(specialization);
//  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    buttonPanel = new javax.swing.JPanel();
    themePanel = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    rbDark = new javax.swing.JRadioButton();
    jPanel2 = new javax.swing.JPanel();
    btnHome = new javax.swing.JButton();
    btnRegister = new javax.swing.JButton();
    btnFamilyMember = new javax.swing.JButton();
    btnSpecialization = new javax.swing.JButton();
    btnSpecialization1 = new javax.swing.JButton();
    btnSpecialization2 = new javax.swing.JButton();
    btnSpecialization3 = new javax.swing.JButton();
    btnSpecialization4 = new javax.swing.JButton();
    btnSpecialization5 = new javax.swing.JButton();
    btnSpecialization6 = new javax.swing.JButton();
    btnSpecialization7 = new javax.swing.JButton();
    basePanel = new javax.swing.JPanel();
    base = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(1920, 1080));

    buttonPanel.setBackground(new java.awt.Color(15, 14, 71));
    buttonPanel.setPreferredSize(new java.awt.Dimension(220, 1080));
    buttonPanel.setLayout(new java.awt.BorderLayout());

    themePanel.setBackground(new java.awt.Color(204, 204, 204));
    themePanel.setPreferredSize(new java.awt.Dimension(150, 100));
    themePanel.setLayout(new java.awt.GridBagLayout());

    jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
    jLabel1.setText("<html><p style=\"color: white;\">Dark Mode</p> </html>");
    jLabel1.setPreferredSize(new java.awt.Dimension(60, 14));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 0);
    themePanel.add(jLabel1, gridBagConstraints);

    rbDark.addActionListener(this::rbDarkActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 14);
    themePanel.add(rbDark, gridBagConstraints);

    buttonPanel.add(themePanel, java.awt.BorderLayout.PAGE_START);

    jPanel2.setBackground(new java.awt.Color(204, 204, 204));
    jPanel2.setLayout(new java.awt.GridBagLayout());

    btnHome.setText("Dashboard");
    btnHome.setOpaque(true);
    btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnHomeMouseEntered(evt);
      }
    });
    btnHome.addActionListener(this::btnHomeActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 1, 0);
    jPanel2.add(btnHome, gridBagConstraints);

    btnRegister.setText("Dev 1");
    btnRegister.addActionListener(this::btnRegisterActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
    jPanel2.add(btnRegister, gridBagConstraints);

    btnFamilyMember.setText("Dev 2");
    btnFamilyMember.addActionListener(this::btnFamilyMemberActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
    jPanel2.add(btnFamilyMember, gridBagConstraints);

    btnSpecialization.setText("Dev 6");
    btnSpecialization.addActionListener(this::btnSpecializationActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 10;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
    jPanel2.add(btnSpecialization, gridBagConstraints);

    btnSpecialization1.setText("Dev 3");
    btnSpecialization1.addActionListener(this::btnSpecialization1ActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 1, 0);
    jPanel2.add(btnSpecialization1, gridBagConstraints);

    btnSpecialization2.setText("Dev 4");
    btnSpecialization2.addActionListener(this::btnSpecialization2ActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 1, 0);
    jPanel2.add(btnSpecialization2, gridBagConstraints);

    btnSpecialization3.setText("Dev 9");
    btnSpecialization3.addActionListener(this::btnSpecialization3ActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 13;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
    jPanel2.add(btnSpecialization3, gridBagConstraints);

    btnSpecialization4.setText("Dev 5");
    btnSpecialization4.addActionListener(this::btnSpecialization4ActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
    jPanel2.add(btnSpecialization4, gridBagConstraints);

    btnSpecialization5.setText("Dev 7");
    btnSpecialization5.addActionListener(this::btnSpecialization5ActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 11;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
    jPanel2.add(btnSpecialization5, gridBagConstraints);

    btnSpecialization6.setText("Dev 7");
    btnSpecialization6.addActionListener(this::btnSpecialization6ActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 14;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
    jPanel2.add(btnSpecialization6, gridBagConstraints);

    btnSpecialization7.setText("Dev 8");
    btnSpecialization7.addActionListener(this::btnSpecialization7ActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 12;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
    jPanel2.add(btnSpecialization7, gridBagConstraints);

    buttonPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

    getContentPane().add(buttonPanel, java.awt.BorderLayout.LINE_START);

    basePanel.setLayout(new java.awt.BorderLayout());

    javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
    base.setLayout(baseLayout);
    baseLayout.setHorizontalGroup(
      baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 550, Short.MAX_VALUE)
    );
    baseLayout.setVerticalGroup(
      baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 520, Short.MAX_VALUE)
    );

    basePanel.add(base, java.awt.BorderLayout.CENTER);

    getContentPane().add(basePanel, java.awt.BorderLayout.CENTER);

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
    home();
  }//GEN-LAST:event_btnHomeActionPerformed

  private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
   // studentRegister();
  }//GEN-LAST:event_btnRegisterActionPerformed

  private void btnFamilyMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamilyMemberActionPerformed
    //familyMember();
  }//GEN-LAST:event_btnFamilyMemberActionPerformed

  private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered

  }//GEN-LAST:event_btnHomeMouseEntered

  private void btnSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpecializationActionPerformed
    //specialization();
  }//GEN-LAST:event_btnSpecializationActionPerformed

  private void rbDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDarkActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_rbDarkActionPerformed

  private void btnSpecialization1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpecialization1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnSpecialization1ActionPerformed

  private void btnSpecialization2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpecialization2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnSpecialization2ActionPerformed

  private void btnSpecialization3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpecialization3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnSpecialization3ActionPerformed

  private void btnSpecialization4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpecialization4ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnSpecialization4ActionPerformed

  private void btnSpecialization5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpecialization5ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnSpecialization5ActionPerformed

  private void btnSpecialization6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpecialization6ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnSpecialization6ActionPerformed

  private void btnSpecialization7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpecialization7ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnSpecialization7ActionPerformed

  private void home() {
   // Default defaultCard = new Default();
    //switchPanel(defaultCard);
  }

  private void switchPanel(javax.swing.JPanel panel) {
    basePanel.removeAll();
    basePanel.add(panel, java.awt.BorderLayout.CENTER);
    basePanel.revalidate();
    basePanel.repaint();
  }

  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//      logger.log(java.util.logging.Level.SEVERE, null, ex);
//    }
//    //</editor-fold>
//    try {
//      FlatLightLaf.setup();
//      //FlatDarkLaf.setup(); // Dark Theme ကြိုက်ပါက ဒါကို သုံးပါ
//
//      // Native Window Decoration (Title Bar ကိုပါ FlatLaf Style ပြောင်းချင်ပါက)
//      UIManager.put("TitlePane.unifiedBackground", true);
//      UIManager.put("Button.arc", 40);
//      UIManager.put("TextComponent.arc", 9);
//      UIManager.put("Component.focusWidth", 1);
//
//    } catch (Exception ex) {
//      System.err.println("Failed to initialize FlatLaf look and feel");
//    }
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
//  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel base;
  private javax.swing.JPanel basePanel;
  private javax.swing.JButton btnFamilyMember;
  private javax.swing.JButton btnHome;
  private javax.swing.JButton btnRegister;
  private javax.swing.JButton btnSpecialization;
  private javax.swing.JButton btnSpecialization1;
  private javax.swing.JButton btnSpecialization2;
  private javax.swing.JButton btnSpecialization3;
  private javax.swing.JButton btnSpecialization4;
  private javax.swing.JButton btnSpecialization5;
  private javax.swing.JButton btnSpecialization6;
  private javax.swing.JButton btnSpecialization7;
  private javax.swing.JPanel buttonPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JRadioButton rbDark;
  private javax.swing.JPanel themePanel;
  // End of variables declaration//GEN-END:variables
}
